models:
  - name: Qwen3-VL-8B-Instruct
    alias: qwen3-vl-chat-8b-instruct
    task: chat
    backend: vllm
    model_path: /nas_data/zhousj/qwen-vl
    dtype: bfloat16
    tensor_parallel_size: 1
    max_model_len: 4096
    cpu_per_replica: 4
    gpu_per_replica: 0.6
    gpu_memory_utilization: 0.40
    min_replicas: 1
    max_replicas: 2
    capabilities:
      - streaming
    labels:
      - internal
      - llm

  - name: Qwen3-8B
    alias: qwen3-8b
    task: chat
    backend: vllm
    model_path: /nas_data/models/Qwen/Qwen3-8B
    dtype: bfloat16
    tensor_parallel_size: 1
    max_model_len: 8192
    cpu_per_replica: 4
    gpu_per_replica: 0.6
    gpu_memory_utilization: 0.4
    min_replicas: 1
    max_replicas: 2
    labels:
      - internal
      - llm

  # - name: bge-reranker-v2-m3
  #   alias: bge-rerank
  #   task: rerank
  #   backend: vllm
  #   model_path: BAAI/bge-reranker-v2-m3
  #   dtype: float16
  #   tensor_parallel_size: 1
  #   max_model_len: 4096
  #   cpu_per_replica: 4
  #   gpu_per_replica: 1
  #   min_replicas: 1
  #   max_replicas: 2
  #   labels:
  #     - internal
  #     - rerank
